language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# Latest node
before_install:
  - nvm install 8.3.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH=$HOME/.yarn/bin:$PATH
# Install dependencies
install:
  - yarn install
  - yarn build
  - yarn copy
  - cd py
  - pip install -U pip
  - pip install swiglpk --only-binary swiglpk
  - pip install -e .
  - cd ..
# Run tests
script:
  - yarn test
#  - if [[ $TRAVIS_PYTHON_VERSION = '3.6' ]]; then yarn coverage; fi
  - cd py
  - python setup.py test
  - cd ..
  - npm run build
# No emails
notifications:
  email: false
# Run with containers
sudo: false
deploy:
  provider: npm
  email: matyas.fodor@gmail.com
  api_key:
    secure: VFFgK9wb0f0dmPsme5F6uDEm/yMaJdxetWFjUw1iJ+nxwpVSob1rkNz9wTfuWFC/E5o8YUg+LIXbYYuWE3pnPgB28gbbUPh33Z5wmnozU80biyZPZVZ9dClTmiWulzu/UnM/4oLBJKSvn6ZJAbHJgXTq0Zoxrj1wXTKZQbEEZ3P42uRyoNNmxbfyemQKYf/Inv8IBetjXlogUs9+1V1drMHjCuDRIdY2W5BoQqnusWirhVmMkYu/QaZFEbtnEH0lPD+ylYPn3PQattxN+BWEUFWyLQHPKToVu8SUcwQYr83Gb6P59YuMaSX+HsMe/4AMdNJMFniKef4Kv8Df18TKYNNgWIMGoWP5veevWzn8yCIRccD+U0IwEOKAVCt0kovJoDJsqvEnmTpY/IPohOM5OdcSPkpHws1bZVJO6ko0jullpwP4Ox1bxWwkESOYPz2oO6XWrF0edPnFpHCXerOK1i+vJNv/pHfUgIiQ95IIjbxiDiX+EuRyhF/H8PFYD7ZoWfPM1ioSgfPAfL2E7flbKF1Q1zCZ7fRde1oD8hb1/nrxaJoMg+dH83GUS+yameqQlIVCZfHC96wMlW+YIqLxLTeVVZ4jECtU5fqStSAkn0dQuayKjN5RldCDJbk5gjpmtDnrAvpqGVSx/dOIel3Y/Zp+BM4o6n2yBvO0Xtcspn0=
  on:
    tags: true
    repo: DD-DeCaF/escher
  skip_cleanup: true