
language: node_js
node_js: 8
addons:
  chrome: stable
<<<<<<< HEAD
=======
before_script:
  - npm install
  # - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
>>>>>>> c6fff68... trying to fix dependency issue
script:
  - ls js/src/
  - npm test
  # - npm publish
cache:
  directories:
    - node_modules
